### ISSUE TITLE
Rework sorting by multiple attributes

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#11]
We need to avoid and remove data type `Multiple`. Problem with this type is that it hides inner data types (which there may be multiple) and there is also problem how to describe this type to the end users. We need to stick to analogies to existing and well established data store - primarily SQL. On the other hand we need to allow both these scenarios:

- sort by two or more attributes in "expected way" - i.e. secondary ordering decides order of elements when primary ordering cannot decide because values are the same
- sort by two or more attributes when the sorting handles "NULLs" last scenario - i.e. there is no attribute found for primary attribute in an entity

We also want to avoid situation where we would need to compare values of the entities in real-time. We already know it's slower than current masking process for pre-sorted arrays. This was the original reason why `Multiple` constraint exists in the first place.

The proposed solution discussed with @lho is:

- add support for creating multi-attribute sort indexes in EntitySchema  / Reference schema by adding so called SortableAttributeCompounds which will aggregate sort direction for multiple existing attributes (which doesn't need necessarily to be sortable themselves)

The final composition would like this:

```
attribute(nameOfCompound, DESC)
```

- [X] we should also relax on requiring that sortable reference attribute is present in entity only once, when multiple references are selected the sort order should be combined:
   - in case of hierarchy reference by a deep traversal order of the filter matching hierarchy tree
   - in case of plain referenced entities by a ascending order of their primary keys

**Comment by lukashornych** [comment]
In order to support multiple attribute names in order constraints we will not use classifiers for it, instead we use value annotation. But this way we cannot have 2 same constraints on the same level. Thus, we introduce array into orderBy with implicit container but unlike in filterBy where we use AND for it, here we just flat children into parent container.

```json
{
  orderBy: [
	{
	  "attributeCodenatural": DESC,
	  "attributeNatural": {}
	},
	{
	  "attributeNatural": {},
	  "entityproperty": {

	  }
	}
  ]
}
```

**Comment by novoj** [comment]
Implemented by my side. I'd need help from @lho here - see TODOs in commit https://github.com/FgForrest/evitaDB/commit/ac201f5cf38974339fbbf5823f2a336800f7534d

**Comment by novoj** [comment]
I've added two additional TODOs for missing tests

**Comment by lukashornych** [comment]
TODOs that were on me are done.

**Comment by novoj** [comment]
Cool, tests are passing, we're finally done.
