### ISSUE TITLE
It's possible to create reference targetting non-existing evitaDB entity type

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#162]
This should clearly not be possible.

**Comment by novoj** [comment]
Unfortunately, this issue was created in a hurry without a proper description of what it really means. Closed for now - if it's a problem, it should come up again.

**Comment by lukashornych** [comment]
@novoj I think it was created when I was writing the "Write data" docs chapter, where it allowed me to create reference to evitaDB-managed `brand` and `category` entities but these entities where not created yet. I think in GQL it wasn't possible because I was internally looking for schema of that entities, but directly in Java it was possible.

**Comment by novoj** [comment]
Thank you! I will fix it today then.

**Comment by novoj** [comment]
This implementation broke a lot of tests and I'm afraid it would break current clients as well. I think we need to postpone validation and allow multiple schemas to be defined in bulk to avoid unnecessary complexity on the client side while maintaining model consistency.

Current use case:

Product -> References Category
category -> references products (related products specified at category level)

It's a circular dependency, but it's a real use case that we need to support. The only situation to avoid the exception would be

1. create category
2. create product that references category
3. change category to reference related products

This requires quite complicated setup on the client side, which now uses the `ClassAnalyzer` facility to set up the schema.

So a new suggestion would be to validate the schema not in the mutation, but at the end of the updateSchema method. In `io.evitadb.core.EvitaSession#updateCatalogSchema` method the validation will be done after all mutations have been processed. This would allow to set up circular dependent updates in one go and still pass the validation.

**Comment by novoj** [comment]
Few grey hairs later ... it's finally done.
