### ISSUE TITLE
Docs: syntax code blocks specific to code language

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#204]
In constraint documentation pages, there syntax code blocks. Currently, they always show EvitaQL syntax no matter the selected code language. It would be nice to have these code block specific to the selected code language.

- [ ] propose syntax of syntax code block for individual code languages (possibly close to their documenting best practices) to determine if its even possible
- [ ] implement syntax code block into documentation pages

**Comment by novoj** [comment]
Isn't this issue already finished @lukashornych ?

**Comment by lukashornych** [comment]
@novoj No, we decided that we don't want to do it now.

**Comment by lukashornych** [comment]
The idea is to create GraphQL/REST API versions of these syntax blocks for each constraint:

![image](https://github.com/FgForrest/evitaDB/assets/13931450/9d09ac71-006b-4452-a627-aaf856df9b91)

with something like following syntax:

```
and: [FilterContainer!]
---
attribute{attribute-name}GreaterThan: String!
---
hierarchy{reference-name}Within: {
  ofParent: FilterContainer!
}
```
which would be similar to how these constraints are written in GraphQL/REST queries.

This would also mean that we would have create custom arg descriptions

![image](https://github.com/FgForrest/evitaDB/assets/13931450/6786f218-d374-4e99-9f28-8f0c0dd75ec6)

because these would not be same for GraphQL/REST.

All of this would have to be probably manually created and would take a lot of time. Also, the current evitaQL syntax format should be somewhat readable even by users using the GraphQL/REST APIs.  That's why we will not invest time into implementing this right now.
