### ISSUE TITLE
Profile large query rendering in REST / GraphQL

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#223]
Our frontend Next.JS developers will request following query in a cart on regular basis:

```graphql
query pickupPointsByShippingType(
  $locale: PickupPointLocale = cs
  $shippingType: String = "ZASILKOVNA"
) {
  queryPickupPoint(
    filterBy: {
      entityLocaleEquals: $locale
      attributeShippingTypeEquals: $shippingType
    }
  ) {
    recordPage(size: 10000) {
      data {
        attributes {
          code
          name
        }
        associatedData {
          pickupPointDetails
          localization
        }
      }      
    }
    extraResults {
      queryTelemetry
    }
  }
}
```

The REST API variant is:

```rest
{
  "filterBy": {
    "entityLocaleEquals": "cs",
    "attributeShippingTypeEquals": "ZASILKOVNA"
  },
  "require": {
"page" : {     
      "size" : 10000
    },
    "entityFetch": {
      "attributeContent": ["code","name"],
      "associatedDataContent": ["pickupPointDetails", "localization"]
    },
    "queryTelemetry": true
  }
}
```

The number of all pickup points in the database is about 8500 tousands. The generated output is 8MB of size (1MB compressed) and evitaDB computes it in about 500ms (most of the time is spent on fetching the data). The GraphQL adds another 700ms, the REST adds 1700ms (the REST is slower than GraphQL in this scenario). The overhead times contains the network costs for transferring the file which will not be negligible.

Can we profile this example query and reveal the spots where it slows down? The price for the text rendering seems too high for me.

**Comment by lukashornych** [comment]
Several optimizations in GQL and REST APIs were made and can be seen in https://github.com/FgForrest/evitaDB/commit/53b099645c806a269c3ed3d2d734865a44270564.
