### ISSUE TITLE
Cannot create catalog if corrupted is present

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#270]
When there is a loaded corrupted catalog, new catalog cannot be created because evitaDB tries to verify name collisions but cannot get schema for the corrupted catalog so it throws `CatalogCorruptedException`.

**Comment by novoj** [comment]
Fixnuto v branchi, ještě jsem doplnil test `io.evitadb.core.EvitaTest#shouldReplaceCorruptedCatalogWithCorrectOne`, který teď padá v GraphQLManageru - mohl bys ho prosím ještě opravit ty?
