### ISSUE TITLE
Error should be thrown when ordering by localised attribute without specifying entityLocaleEquals in filter

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#280]
This query should return an exception since it doesn't specify a locale in a filter.

``` graphql
query {
  listProduct (filterBy: { attributeNameStartsWith: "M" }, orderBy: { attributeNameNatural: ASC } ) {
    attributes(locale: cs) {
      code
      name
    }
  }
}
```

**Comment by novoj** [comment]
@lukashornych can you look at the commit if I correctly updated your GraphQL tests and if you don't want to add more tests?

**Comment by lukashornych** [comment]
@novoj it seems okay to me. Thanks!
