### ISSUE TITLE
New boolean marker for attribute `representative`

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#281]
For better orientation in evitaLab it would be nice to be able to mark one or more attributes as `representative` attributes of the entity. Values of those attributes will be used in evitaLab instead of primary key when displaying value of the reference in the table cell. Representative attributes will be also automatically displayed along with entity data in the default entity listing view.

If there are more of such attributes they will be rendered next to each other joined by comma. If the attribute is localized, it will be displayed in the cell only if the language is selected. The order of the representative attributes will be driven by the order of the attribute in the entity schema.

Is it correct @lukashornych?

**Comment by lukashornych** [comment]
Yeah, thats correct. Especially, I like the idea of using these attributes for rendering default grid view.

**Comment by novoj** [comment]
It turned out to be quite a challenge. I had to split the AttributeSchema into two different schemas:

- EntityAttributeSchemaContract (used on entity level, contains representative marker)
- AttributeSchemaContract (used on reference level, doesn't contain representative marker)

This led to an abstraction changes and generics tweaks along the codebase. Can you @Khertys check how much work will it take to adapt C# client and the schema builders?

@lukashornych there are a few TODOs for you in the codebase where I wasn't sure with the refactor in APIs. Also can you alter the evitaLab to take the representative flag into an account? I'll provide you with an example index in follow-up comment.

**Comment by novoj** [comment]
The new data set is available at:

```
wget https://evitadb.io/download/representative-moda.zip
```

**Comment by lukashornych** [comment]
@novoj GQL/REST APIs are finished. I'll try to quickly implement it in the evitaLab and let you know.

**Comment by lukashornych** [comment]
@novoj evitaLab is finished and released and merged into evitaDB in #281 branch ready to be released.

**Comment by novoj** [comment]
Merged into `dev`.
