### ISSUE TITLE
Honour the original catalogue / entity type name

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#291]
The catalogue names are converted using KEBAB case to a name that is used in the URL in GraphQL and REST API. Unfortunately, this confuses developers in certain situations. For example, if they name a catalogue in the following form: `name_of_the_client`, the URL `/name_of_the_client` won't work because the correct KEBAB form is `/name-of-the-client`. The same problem applies to entity names that are also part of the url.

We should reconsider this behaviour. Both the catalogue name and the entity type names are somehow validated for allowed characters, so if we check the validation rules we might be able to safely use the original names (in lower case) instead of the KEBAB variants.

**Comment by lukashornych** [comment]
In GQL, we are concerned only with catalog names in URLs. These are already strictly validated to use only ASCII + `-_` characters so the only thing is to registers GQL handlers to both URLs. 
- [ ] add support for multiple URLs for single GQL instance
- [ ] register single GQL handler to all generated URLs
- [ ] generate all alternative URLs for single GQL instance
- [ ] implement support for unregistering all URLs connected to the GQL catalog instance

In REST, we are concerned with both catalog names and entity types in URLs. Entity types are not as strictly validated as catalog names and can contain all sorts of different characters. This is solvable for client using escaping, but I don't know how the Undertow router will react to it yet.
- [ ] analyze how to add path into Undertow handler with characters that need to be escaped by client
- [ ] add support for multiple URLs for REST API catalog/collection endpoints
- [ ] generate all alternative REST URLs for catalogs AND for collections
- [ ] implement support for unregistering all URLs connected to the REST catalog/collections endpoints

**Comment by novoj** [comment]
On second thought, do we need multiple names? Shouldn't we consider the validation rules to match what we need in the URL representation and always use the original form? Doesn't multiple URLs add another "endpoint" to our already long Open API schema?

**Comment by lukashornych** [comment]
That's option too. You are right that it would probably make the OpenAPI endpoint definition part 4x bigger.
However, it would greatly limit the possible entity types. On the other hand, other database systems e.g. SQL, also don't support all sorts of different characters in table names, so yeah, I agree with you @novoj we should probably use similar validation pattern for all classifier we use for catalog names. However, it will be breaking change for Next.js team and evitaLab.

- [ ] analyze what characters are safe to use in URL as path item

**Comment by novoj** [comment]
Yes, it would be a breaking change, but in the case of GraphQL it would only affect the catalogue name - entity types are not part of the url, they're part of the query, which is not affected by this change. Am I right?

**Comment by lukashornych** [comment]
Yes, that's correct.

**Comment by novoj** [comment]
So it's not such a big deal for them.

**Comment by lukashornych** [comment]
No, just that we need to tell them :smile:

**Comment by lukashornych** [comment]
@novoj should we do the characters limitation only on catalog names and entity type or in all classifiers? I'm asking you because you were originally the one who wanted to have liberty in naming (spaces, special characters, and so on).

**Comment by novoj** [comment]
The result of a Discord discussion is that we will support single pattern for all classifiers and catalogue names: `(^[\p{Alpha}][\p{Alnum}_.\-~]*$)`

**Comment by lukashornych** [comment]
The evitaDB part is done. But I need to update evitaLab in one go, otherwise it will not work.

**Comment by lukashornych** [comment]
evitaLab updated as-well. Can I merge it into `dev`, or do you plan to release something else an thus we cannot break Next.js team?

**Comment by novoj** [comment]
Not yet, please I'd like to merge it all at once with https://github.com/FgForrest/evitaDB/issues/281 since it both breakes backward compatibility.

**Comment by novoj** [comment]
Merged to `dev`.
