### ISSUE TITLE
Provide access logs

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#292]
We need to be able to generate access log from the Undertow / gRPC API endpoints to be able to track possible communication issues. Currently there is no such option in evitaDB. The access log should be written using standard `Slf4J` logging facility. The target (different file) will be configured in the logging configuration.

**Comment by lukashornych** [comment]
Access logging for Undertow and gRPC APIs is implemented. It uses `ACCESS_LOG` marker to distinguish access log messages from standard app messages.
