### ISSUE TITLE
Support quotation marks as alternative String wrapper in evitaQL

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#295]
Currently the strings in evitaQL are wrapped inside apostrophes: `'this is a string'`, but in the main supported languages Java/C# are strings wrapped inside quotation marks: `"this is a string"`. This fact prevents copying the Java/C# query directly in evitaLab and manual transformation is required.

If we'd supported both variants (similar to JavaScript), we could make the testing Java/C# queries in evitaLab easier. Also we should support some kind of escaping of those characters inside the string using for example backslash character `\'` or `\"`. So that following query is possible: `attributeEquals('code', 'Dog hasn't eaten yet. Call for \"help\"')`

**Comment by lukashornych** [comment]
The support for `"` was added and released. The escaping support will be implemented later as its more tricky.

**Comment by novoj** [comment]
What escape character was used finally? Where is it documented?

**Comment by lukashornych** [comment]
Standard `\`, you can look here io.evitadb.api.query.parser.visitor.EvitaQLValueTokenVisitorTest#validStringLiterals. I quess I could document it in the query basics :thinking: will do.

**Comment by novoj** [comment]
Please document it, thanks!
