### ISSUE TITLE
Add `requested` property to `Hierarchy` and `AttributeHistogram` extra results

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#304]
In order to visualize the current filter in the evitaLab visualization tab, we need to propagate the information about the requested parts to the extra results:

## Hierarchy

The entity within each hierarchy that is directly selected by the `hierarchyWithin` constraint is marked as `requested`.

## AttributeHistogram

The bucket containing the lower or upper threshold of the `attributeBetween` (inclusive) or within those thresholds will be marked as `requested`.

- [ ] also document this new feature in existing documentation

**Comment by novoj** [comment]
@lukashornych Can you please add GQL support + correct the REST tests? And finally test the new property in evitaLab. Finally you can merge the feature to dev/master and after that we will regenerate documentation test snippets. Thank you.

**Comment by lukashornych** [comment]
@novoj Added support into GQL and REST with new tests. In evitaLab it seems to return correct histograms.

**Comment by lukashornych** [comment]
Reopening because I've totally forgot about the hierarchy support...

**Comment by lukashornych** [comment]
Also @Khertys could you prepare support into the C# client?

**Comment by novoj** [comment]
The gRPC translation on Java side is ready. The change should be compatible with previous version. But we should propagate it also to the C# client ... you're right.

**Comment by lukashornych** [comment]
@novoj @Khertys I've implemented the `requested` into the hierarchy trees and updated the hierarchy doc. examples. 
@Khertys Let me know when you have the C# client ready so we can test the docs and close it.

**Comment by lukashornych** [comment]
C# client updated
