### ISSUE TITLE
REST API doesn't use camelCase notation for attributes etc. into result JSON

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#306]
I've discovered that REST API uses original case for attributes, associated data, references, etc. when serializing query result into JSON. This may cause issues on some clients that cannot work e.g. with kebab-case notation.
Also, the GQL API also use camelCase variants of these data, so it should probably be the same in REST API.

cc @novoj

**Comment by novoj** [comment]
I agree, can we please fix it before someone starts using REST API regularly?
