### ISSUE TITLE
Invalid DateTime format on EvitaQL ToString method 

### ISSUE THREAD

**Issue by milossamek** [FgForrest/evitaDB#320]
For debugging EvitaQL query I use the method: `io.evitadb.api.query.Query#toString`

When converting a query, a sample query is generated:
```
query(
collection('Product'),
filterBy(
          entityPrimaryKeyInSet(114161),
          entityLocaleEquals('cs'),
          or(
              attributeIs('validity', NULL),
              attributeInRange('validity', 2023-11-08T07:26:54.683+01:00)
          ),
              attributeInSet('status', 'ACTIVE'),
              priceInCurrency('CZK'),
),
require(
         page(1, 20),
         entityFetch(
                      attributeContentAll(),
                      priceContentRespectingFilter('reference')
          )
        )
)
```

as you can see the date format contains the precision on milliseconds, but the supported precision for EvitaQL is set to seconds. 

Later, when I want to use the string formated query in the EvitaLab, i get the response:

```
{
  "errorCode": "73a20adb22d95068d7daa5f6e2d96230:af7e03290249dcf135c6dd7ad7cd6bc9:92",
  "message": "Invalid query, error at position 8:62: Unexpected token, expected: ')'"
}
```

response, which could make it more readable that a badly formatted date is being passed

**Comment by lukashornych** [comment]
The seconds fraction is implemented. 

Regarding the:
> response, which could make it more readable that a badly formatted date is being passed

unfortunately, the evitaQL is currently not data-aware (while parsing, we don't know expected type of the `validity` attribute) and thus the parser doesn't know its datetime if its incorrect token because there may be theoretically any value of any supported data type.
