### ISSUE TITLE
Support for JSON-like logging that is more easily digestible by Loki and similar systems in K8S ecosystem

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#337]
### Logging to `stdout` or `stderr`

Preferred option.

- There is no need to deal with rotation - it is provided by K8S itself.
- Allows you to log two separate "streams" - `stdout` and `stderr`. The container can thus log two independent sources, each in its own format.
- K8S automatically adds a timestamp to each line. The application does not need to insert it at all.
- The automatically added Timestamp makes it impossible to log multiline messages (e.g. Java stack-trace) - the multiline message cannot be reconstructed. The solution is to use single line JSON format:

  ```
  { level="info", client_id="1111", ..., message="Exception\n stacktrace line 1\n ..." }
  ```
  
### Logging to file
Fallback option if the application fails to log to `stdout` or `stderr`.
The application must allow to configure (for each log type) the container at startup:
- Log file name prefix
  - the application appends to the prefix
    - the version of the format inside the log file
    - timestamp or sequence number according to the rotation mechanism
- Rotation and deletion mechanism
  - either Size based
    - The size at which the next log file is created.
    - Max. number of log files
  - or Time based
    - Pattern for the timestamp appended to the log file name prefix
    - Max. log file age

E.g:

```
## https://logging.apache.org/log4j/2.x/manual/appenders.html#RollingFileAppender

## /www/log/evita-applog.v01.2023-12-31.23:59
applog.prefix = /www/log/evita-applog/evita-applog.
applog.time.pattern = yyyy-MM-dd.HH:mm
applog.time.maxage = 10m


## /www/log/evita-access.v01
## /www/log/evita-access.v01.1
## /www/log/evita-access.v01.2
access.prefix = /www/log/evita-access/evita-access.
access.size.limit = 100MB
access.size.maxcount = 10
```

The container configuration at startup will be:
- via ENV shell variables: `APPLOG_PREFIX=...; APPLOG_TIME_PATTERN=... `
- or from a separate file that will be added to the container at startup

Even in the case of logging to a file, we prefer JSON single-line format. This allows to dynamically change log entries without having to modify the parsing rules of Promtail that collects the logs. With mandatory `timestamp`, `message` and `level` entries:

```
{ timestamp="2023-11-16T10:50:24.869+01:00", level="INFO", message=" ... something happened ...", client_id="xxx", request_id="yyy", ... }
```

**Comment by lukashornych** [comment]
There are implemented new logback layouts `io.evitadb.server.log.AccessLogJsonLayout` and `io.evitadb.server.log.AppLogJsonLayout` which will use for logging to STDOUT and STDERR for K8S.

Specifically we agreed that we will log app log messages to STDOUT as JSON and access log messages to STDERR as JSON messages:
```xml
<configuration>

	<appender name="STDERR" class="ch.qos.logback.core.ConsoleAppender">
		<target>System.err</target>
		<filter class="io.evitadb.server.log.AccessLogFilter" />
		<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
			<layout class="io.evitadb.server.log.AccessLogJsonLayout"/>
		</encoder>
	</appender>

	<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
		<target>System.out</target>
		<filter class="io.evitadb.server.log.AppLogFilter" />
		<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
			<level>INFO</level>
		</filter>
		<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
			<layout class="io.evitadb.server.log.AppLogJsonLayout"/>
		</encoder>
	</appender>

       <!-- ... -->

</configuration>
```
This we won't need any logging to files with rolling.

**Comment by novoj** [comment]
Can we please alter the whitespace replacing logic to more optimal?!

**Comment by lukashornych** [comment]
@novoj found method `StringUitls#replaceEach` in Apache Commons which seems to do what we need and with some clever logic for when the replacement chars are larger that the replaced chars (which we need).
