### ISSUE TITLE
Optimize method checking classifiers against keywords

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#340]
The method `io.evitadb.utils.ClassifierUtils#isKeyword` is highly unoptimal and slows down indexation of evitaDB data when new schemas are created. 

Solution might be to compare string only by splitting them to words and lowercasing them. Also these variants for keywords would be pre-computed. The actual comparison would happen using Set. The word-splitting should cover all supported cases because all conversion use the same word-splitting and we rule out the delimiter characters.

**Comment by lukashornych** [comment]
@novoj its implemented in `dev`. Could you please test it in our eshop implementation? Had no luck with running the unit tests.

**Comment by novoj** [comment]
The method doesn't represent a problem in the tests performance-wise now. But I doubt it's correct - how does this:

```java
return StringUtils.splitStringWithCaseIntoWords(classifier)
			.stream()
			.map(String::toLowerCase)
			.collect(Collectors.joining());
```

differ from

```java
return classifier.toLowerCase();
```

?

I tried what I think is a more correct implementation here: https://github.com/FgForrest/evitaDB/tree/issue-340-classifier-validation

But the test ceased to pass on line:

```java
assertThrows(InvalidClassifierFormatException.class, () -> validateClassifierFormat(ClassifierType.ATTRIBUTE, "primarykey"));
```

But this doesn't play well with word splitting - it suggests that plain lowercase is sufficient for conflict detection. Can you please elaborate on this?

**Comment by novoj** [comment]
Super! Will you merge it then and close the issue?
