### ISSUE TITLE
Don't generate mutations in GQL/REST if evita is in read-only mode (discussion)

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#371]
We generate mutations in GQL and REST APIs everytime, even if the evita instance is in a read-only mode and thus the mutations will never succeed. 

Should we omit `update*Schema`, `upsert*`, `createCatalog` and another mutating GQL mutations, as-well as mutating REST endpoints? The evita instance will not let any mutations to be applied, but I think that if this is instance-wide mode, we should modify the generation according to it, so it doesn't make confusion that it is possible to modify the instance. I think it's similar to authorization when only certain users would see certain fields (https://www.graphql-java.com/documentation/field-visibility).

**Comment by novoj** [comment]
So far there is only one incarnation of the read-only evitaDB instance and it is a demo site. Although there may be use cases where others will use this setting, it will probably always be an edge case.

So even if it sounds right, I'd only try it if the workload associated with the changes is minimal.

As you said - for authorization tasks we'd probably use a different approach.

**Comment by lukashornych** [comment]
It would be a few if conditions in the schema generator. I agree that it is edge case, so I will close it for now as it is not something we would benefit from right now.
