### ISSUE TITLE
Cannot fetch bodies for multiple entities from multiple collections

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#392]
When using multiple globally unique identifiers in single query to fetch entities where each entity is from different collection AND entity body is wanted, like so:
```
query(
  filterBy(
    attributeInSet("url", "/en/macbook-pro-13-2022", "/en/cell-phones"),
    entityLocaleEquals("en")
  ),
  require(
    entityFetch(
      attributeContent("code")
    )
  )
)
```
evitaDB returns error 
```
Entity `Product` with primary key `63049` cannot be enriched because it has been already removed.
```
If both URLs would target the same collection, both entities would be returned with their bodies as expected.

I've prepared test in `bugfix-392-multiple-entities-body-error` called `io.evitadb.api.EntityByAttributeFilteringFunctionalTest#shouldReturnEntitiesFromDifferentCollectionsByEqualsToGlobalLocalizedAttribute` which behaves slightly different but I think the core problem is the same. 
In the test, both entities returned same attributes (same body parts?), in demo data there is no body part found.

**Comment by novoj** [comment]
The test is passing now - changes were merged to `dev`. Can you verify the use-case you mentioned manually? Does this fix also fixes that use-case?

**Comment by lukashornych** [comment]
Weird, even though the test is passing, when I try to run the mentioned query manually against our demo dataset, the original error is still there, must by something related to the actual data.

**Comment by novoj** [comment]
Problem simulated manually and fixed. Test altered to invoke the desired behaviour.
