### ISSUE TITLE
System / gRPC API should provide information about evitaDB server version

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#406]
We need to provide sever version in gRPC evitaLab API, so then the clients can visualize it and reason about it. We should also provide a method to detect the client version. Java client should log an error/warning if its minor version differs from the server version, as it might signal compatibility problems.

**Comment by lukashornych** [comment]
At this point I suggest to create an endpoint in the system API that would return simplified info about the evitaDB instance like we've already talked about.

Because we already need server name and evitaDB version and evitaLab would benefit from list of running APIs with their URLs (even though this could be separate API in the lab API):
```json
{
  "serverName": "evitadb",
  "version": "1.0.0",
  "apis": [
    "graphql": {
      "url": "https://localhost:5555/gql"
    }
  ]
}
```

**Comment by novoj** [comment]
We need to consider that this endpoint will sometimes need to be behind authentication in the future. The server must not return its version to an unauthenticated client for security reasons.

**Comment by lukashornych** [comment]
We could return differently rich objects based on authentication. E.g. for non-authenticated:
```
{
  "serverName": "evitadb"
}
```
and for authenticated as I mentioned above.

Yeah if would have different endpoints for these, would easily setup the auth. rules based on endpoint paths, but the REST API will definitely have to have some tools for enabling/disabling returned properties, which we could maybe reuse here and have single endpoint.

**Comment by novoj** [comment]
gRPC implementation and compatibility check in client is done. Tomorrow I'll implement the system endpoint.
