### ISSUE TITLE
AttributeInSet constraint is removed from query if empty

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#413]
The current behaviour for the `attributeInSet` constraint is that it is automatically removed from an input query if it doesn't contain any values (same for both `null` and empty arrays). We want to preserve this logic if a developer passes a `null` directly like so 
```
attributeInSet("code", null)
```
because this way we can more easily construct queries with optional constraints based on present of a value and we don't need to "if" every constraint.
However in scenario where a empty array is directly passed into the constraint like so:
```
attributeInSet("code", [])
```
it should be preserved and ultimately return empty list of entities. Right now, it returns first page of 20 entities which is confusing.

**Adept constraints:**

- [x] `PriceInPriceLists`
- [x] `AttributeInSet`
- [x] `EntityPrimaryKeyInSet`

**Comment by novoj** [comment]
We should probably do the same for `primaryKeyInSet` and look out for other similar constraints that should behave the same.

**Comment by lukashornych** [comment]
@novoj Yeah, I'll do that

**Comment by novoj** [comment]
> @novoj Yeah, I'll do that

That was a reminder for me - I count that I will take care of this issue (maybe except the parser part).

**Comment by novoj** [comment]
Implemented except parser - tests for parser updated and currently they don't pass. Can you please look at it @lukashornych?
