### ISSUE TITLE
Min/max offset date times returned by APIs have zone offsets with seconds

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#424]
If for example attribute has DateTimeRange type and OffsetDateTime.MIN/MAX are used signalizing infinity, the DateTimeFormatter returns seconds in zone offset `+00:57:44` which cannot be parsed by JavaScript as it is not valid ISO zone offset apparently. It should return only hours and minutes.

**Comment by lukashornych** [comment]
After some digging, the problem is not with `OffsetDateTime.MIN` used by evitaDB (that formats correctly to `-999999999-01-01T00:00:00+18:00`). Problem was locally in demo dataset.

**Comment by novoj** [comment]
The problem was caused by conversion `LocalDateTime.MIN/MAX.atZone(ZoneId.systemDefault()).toOffsetDateTime()` which produced different (unaligned date times).
