### ISSUE TITLE
Trailing comma in evitaQL

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#493]
When parts of the query are commented out or lines are moved, there is usually a parsing error due to the trailing comma. If our parser automatically ignores the last comma if there is no additional child constraint, we could make life easier for developers.

What is your opinion on this @lukashornych ?

**Comment by lukashornych** [comment]
The only thing I have against it, is that developers leave these trailing commas and it makes a mess, but that's not really a reason not to do it. I agree that it could be useful. I'll check what it would mean to implement it.
