### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#5]
Revisit our initial documentation and create basis of the technical documentation for the consumers. The structure of the planned developer documentation is as follows:

## Get started

1. Run evitaDB
   1. Run embedded in you application
   2. Run as service inside Docker
2. Create your first database
3. Query our dataset

## Use

1. Data model
   1. Data types
   2. Schema
2. Connectors
   1. GraphQL
   2. REST
   3. gRPC
   4. Java
   5. C#
3. API
   1. Define schema
   2. Upsert data
   3. Query data
   4. Write tests
   5. Troubleshoot

## Query

1. Basics
2. Filtering
   1. Bitwise
   2. Boolean
   3. Comparable
   4. String
   5. Locale
   6. Range
   7. Price
   8. References
   9. Hierarchy
   10. Facet
3. Ordering
   1. Natural
   2. Price
   3. Reference
   4. Random
4. Requirements
   1. Paging
   2. Fetching
   3. Price
   4. Hierarchy
   5. Facet
   6. Histogram

## Operate

1. Configure
   1. Setup TLS
2. Run
3. Backup & Restore
4. Monitor

## Deep dive

1. Storage model
2. Bulk vs. incremental indexing
3. Transactions
4. Cache
5. Observe changes

## Solve

1. Render category menu
   1. Mega-menu
   2. Partial menu
   3. Hide parts of the category menu
2. Filter products in category
   1. With faceted search
   2. With price filter
3. Render referenced brand
   1. With product listing
   2. With involved categories listing
4. Handle images & binaries
5. Model price policies

**Comment by lukashornych** [comment]
Note to myself: several examples tests were marked with `ignoreTest` because we don't have support for custom instaces of GQL and REST, mainly we don't have way to specify server to point to.

**Comment by novoj** [comment]
We could add another attribute to the component widget, if it helps.

**Comment by novoj** [comment]
The issue is almost done - there are two exceptions:

- issue #200 
- and `documentation/user/en/use/api/write-data.md:574`

When these are done, we may close this issue.

**Comment by novoj** [comment]
🥳 🍾 10 months after opening this issue we can finally close it!
