### ISSUE TITLE
Watching for the changes in certificates

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#58]
If a Let's encrypt certificate is configured for the evitaDB server, it is automatically renewed every few months by an external script. The evitaDB, which is configured to use this certificate, currently needs to be restarted to reload the certificate. It would be nice if evitaDB would watch for changes in the file and if the file is changed, it would automatically update it in the internal keyStore.

**Comment by Khertys** [comment]
Relates to #397.

**Comment by novoj** [comment]
Implemented in https://github.com/FgForrest/evitaDB/issues/736, this issue is closed.
