### ISSUE TITLE
Proof read - assignment documentation

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#6]
Please proof read following documents:

- [x] `docs/research/en/assignment/classes/facet_lookup_summary.mdx`
- [x] `docs/research/en/assignment/classes/histogram.mdx`
- [x] `docs/research/en/assignment/model/associated_data_implicit_conversion.mdx`
- [x] `docs/research/en/assignment/model/data_types.mdx`
- [x] `docs/research/en/assignment/querying/price_computation.mdx`
- [x] `docs/research/en/assignment/querying/query_api.mdx`
- [x] `docs/research/en/assignment/querying/query_language.mdx` (this one is quite fat)
- [x] `docs/research/en/assignment/updating/entity_api.mdx`
- [x] `docs/research/en/assignment/updating/schema_api.mdx`
- [x] `docs/research/en/assignment/index.mdx` (also quite big)

**Comment by Gift-505** [comment]
Done, close this issue, please.
