### ISSUE TITLE
Cannot order by reference attribute when not manually fetched

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#647]
When defining order by with attribute natural ordering on reference content without actually requesting the attribute, evitaDB throws error stating that the attribute must be requested:

Error:
```
Attribute `orderInCategory` was not fetched along with the entity. You need to use `attributeContent` requirement in `referenceContent` of your `require` part of the query.
```

Example query
```gql
query listProduct {
    listProduct {
      primaryKey
      categories( orderBy:{ attributeOrderInCategoryNatural: DESC}) {
        referencedEntity {
          primaryKey
        }
      }
    }
  }
```

I suppose the problem is that this sorting is done by the `EntityDecorator` instead of the engine itself, hence the required attribute.
However, I would expect that the evitaDB server would visit the entire query prior to fetching the entites and request such needed attributes by it self.

**Comment by novoj** [comment]
Fixed in #260 branch.
