### ISSUE TITLE
New version of evitaLab is backward incompatible in terms of configuration

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#654]
Problem is with configuration option: `api.endpoints.lab.gui.preconfiguredConnections`

Negotiated steps for correction:

- we remove [evita-configuration.yaml](https://github.com/FgForrest/evitaDB/blob/6e644441b4582621c9abc020c8fc58b924b3530d/evita_server/src/main/resources/evita-configuration.yaml#L105-L105) line from configuration on classpath
- when this line is missing the initial configuration fetch will generate necessary API urls from `api.exposedOn`, and if not defined from local hostname (in other words uses first item in the system / grpc urls here: `io.evitadb.externalApi.configuration.AbstractApiConfiguration#getBaseUrls`)
- the line will stay documented and may be added on any of the project to bootstrap evitaLab connections manually if necessary

**Comment by lukashornych** [comment]
I think we should still mark this as `breaking` change because we'll remove the CLI property to define path for the evitaLab connections.

**Comment by lukashornych** [comment]
Interestingly enough, the `GuiHandler` already works with the `api.exposedOn` so I just removed the `api.endpoints.lab.gui.preconfiguredConnections` CLI property as we've discussed and documented new recommended configuration.

Now we just need to make sure that the `api.exposedOn` is correctly configured, but evitaDB itself should crash anymore.
