### ISSUE TITLE
Proxying for all supported APIs via Lab endpoint

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#659]
It's quite cumbersome to properly configure and make accessible all supported APIs in external environments (K8S) where you need to create port forwarding to access the target API. It would be very convenient to be able to proxy communication to all APIs through a "lab" endpoint.

**Comment by lukashornych** [comment]
This would also greatly simplify configuration of connections in lab itself. Right now, we need separate URLs for each API to be configured in lab (although we want to automate implement auto-discovery, we would still need references behind the scenes). If we had proxy, we would just need single URL and we didn't have to worry about some sort of auto-discovery.

**Comment by lukashornych** [comment]
Also, we would have option to have custom lab API again for tools like API compatibility comparison without need to specify yet another url into evitaDB connection in the lab.

**Comment by novoj** [comment]
Turns out - it does work that way now. Unfortunately, this opens up an attack vector we hadn't thought of. We need to control access via not configured ports between web APIs.

**Comment by novoj** [comment]
Completely implemented and tested. @lukashornych You can count on availability of APIs through Lab port / scheme combination.
