### ISSUE TITLE
Restrict mTLS security only to gRPC service scope

### ISSUE THREAD

**Issue by Khertys** [FgForrest/evitaDB#736]
Enabling mTLS currently breaks all APIs since it forces the user to provide a certificate, but browsers (REST, GraphQL APIs) don't support sending one. With the current implementation in the Armeria web server, we have trouble properly setting up mTLS for this purpose.

With version 1.31 (https://github.com/line/armeria/milestones) released, a new approach to TLS/mTLS configuration will be introduced. It should simplify our internal work with certificate security-related issues. 

The release also contains necessary changes for easier solving https://github.com/FgForrest/evitaDB/issues/58

After this release, these features in eviteDB will be added/updated:
- correction of setting up TLS/mTLS in ExternalApiServer and the EvitaClient
- focus the mTLS restrictions only to mTLS supported APIs - gRPC
- certificate switching in runtime

**Comment by novoj** [comment]
@novoj will upgrade Armeria to server 1.31 which has improved work with TLS and will allow us to handle this issue in a more elegant way. @Khertys will then also fix and test the issue #58

**Comment by novoj** [comment]
I've ugpraded Armeria and other libraries to latest versions in branch `version-upgrade`. I've also attempted to prepare shaded client JAR that requires no dependencies. Can you please try it, and continue with mTLS reimplementation @Khertys?

**Comment by novoj** [comment]
I've gone through the changes and made some refactorings and optimizations - can you review it, please? Commit is: https://github.com/FgForrest/evitaDB/pull/759/commits/17827ba3ffd5a4a3aafb4835761d4bcaf07cdb2d

Also the Markdown documentation wasn't updated. Can you please do it?

**Comment by novoj** [comment]
This issue also closes https://github.com/FgForrest/evitaDB/issues/58
