### ISSUE TITLE
Document gRPC API

### ISSUE THREAD

**Issue by novoj** [FgForrest/evitaDB#9]
We need to document gRPC proto files with comments that would reflect the descriptions in GQL/REST api descriptors. Can @lukashornych please provide more information on how to find proper descriptions for analogous data in the descriptors?

Also we need to write article `docs/user/en/use/connectors/grpc.md`.

**Comment by lukashornych** [comment]
Descriptors are partitioned into multiple packages to reflect GQL and REST APIs but that shouldn't matter for gRPC, just take descriptors from all following packages:

- `io.evitadb.externalApi.api.catalog.dataApi.model`
- `io.evitadb.externalApi.api.catalog.schemaApi.model`
- `io.evitadb.externalApi.api.system.model`

**Comment by novoj** [comment]
Accepted
